/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.authorizer;

import org.junit.Test;

import java.io.StringReader;
import java.io.StringWriter;

import static org.junit.Assert.assertEquals;

public class AppTest {

    public static String multiline(String... args) {
        String newLine = System.getProperty("line.separator");
        return String.join(newLine, args);
    }

    @Test
    public void testIntegrationCardActive() throws Exception {
        StringReader in = new StringReader(
                multiline(
                        "{\"transaction\": {\"merchant\": \"McDonald's\", \"amount\": 31.5, \"time\": \"2019-02-13T09:00:00.000Z\"}}",
                        "{\"account\": {\"active-card\": true, \"available-limit\": 100}}",
                        "{\"account\": {\"active-card\": false, \"available-limit\": 100}}",
                        "{\"transaction\": {\"merchant\": \"Burger King\", \"amount\": 20, \"time\": \"2019-02-13T10:00:00.000Z\"}}",
                        "{\"transaction\": {\"merchant\": \"Habbib's\", \"amount\": 90, \"time\": \"2019-02-13T11:00:00.000Z\"}}",
                        "{\"transaction\": {\"merchant\": \"Bob's Paulista\", \"amount\": 10, \"time\": \"2019-02-13T12:00:00.000Z\"}}",
                        "{\"transaction\": {\"merchant\": \"Bob's Consolacao\", \"amount\": 10, \"time\": \"2019-02-13T12:00:02.000Z\"}}",
                        "{\"transaction\": {\"merchant\": \"Bob's Metrô\", \"amount\": 10, \"time\": \"2019-02-13T12:00:04.000Z\"}}",
                        "{\"transaction\": {\"merchant\": \"Bob's Metrô\", \"amount\": 10, \"time\": \"2019-02-13T12:00:05.000Z\"}}",
                        "{\"transaction\": {\"merchant\": \"Bob's Rodoviaria\", \"amount\": 10, \"time\": \"2019-02-13T12:01:59.000Z\"}}"
                )
        );
        StringWriter out = new StringWriter();
        App.run(in, out);

        assertEquals(
                "we validate account existence, insufficient-limit, high-frequency and doubled-transaction",
                multiline(
                        "{\"account\":null,\"violations\":[\"account-not-initialized\"]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":100},\"violations\":[]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":100},\"violations\":[\"account-already-initialized\"]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":80},\"violations\":[]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":80},\"violations\":[\"insufficient-limit\"]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":70},\"violations\":[]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":60},\"violations\":[]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":50},\"violations\":[]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":50},\"violations\":[\"high-frequency-small-interval\",\"doubled-transaction\"]}",
                        "{\"account\":{\"active-card\":true,\"available-limit\":50},\"violations\":[\"high-frequency-small-interval\"]}",
                        ""
                ),
                out.toString()
        );
    }

    @Test
    public void testIntegrationCardNotActive() throws Exception {
        StringReader in = new StringReader(
                multiline(
                        "{\"account\": {\"active-card\": false, \"available-limit\": 100}}",
                        "{\"transaction\": {\"merchant\": \"Burger King\", \"amount\": 20, \"time\": \"2019-02-13T10:00:00.000Z\"}}"
                )
        );
        StringWriter out = new StringWriter();
        App.run(in, out);

        assertEquals(
                "we validate account existence, insufficient-limit, high-frequency and doubled-transaction",
                multiline(
                        "{\"account\":{\"active-card\":false,\"available-limit\":100},\"violations\":[]}",
                        "{\"account\":{\"active-card\":false,\"available-limit\":100},\"violations\":[\"card-not-active\"]}",
                        ""
                ),
                out.toString()
        );
    }
}
